---
# handlers file for roles/tup_tap

- name: start openvpn-server@server
  systemd:
    name: openvpn-server@server
    state: started
    enabled: yes

- name: start openvpn-client@server
  systemd:
    name: openvpn-client@server
    state: started
    enabled: yes

- name: restart network
  systemd:
    name: network
    state: restarted
